"""init schema

Revision ID: 3373347030cf
Revises: 
Create Date: 2026-01-26 13:44:37.856841

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3373347030cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), server_default='USA', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'ticker', name='uq_companies_name_ticker')
    )
    op.create_table('company_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country_risk_premium',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('india', sa.Float(), nullable=False),
    sa.Column('china', sa.Float(), nullable=False),
    sa.Column('japan', sa.Float(), nullable=False),
    sa.Column('us', sa.Float(), nullable=False),
    sa.Column('uk', sa.Float(), nullable=False),
    sa.Column('uae', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('growth_weight_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor')
    )
    op.create_table('implied_equity_risk_premium_usa',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('implied_erp', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('index_annual_price_movement',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('nasdaq_composite', sa.Float(), nullable=False),
    sa.Column('sp500', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('industry_betas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_industry_bucket', sa.Text(), nullable=False),
    sa.Column('mapped_sector', sa.Text(), nullable=False),
    sa.Column('unlevered_beta', sa.Float(), nullable=False),
    sa.Column('cash_adjusted_beta', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_industry_bucket', 'mapped_sector', name='uq_industry_betas_bucket_sector')
    )
    op.create_table('marginal_corporate_tax_rates',
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('effective_rate', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('country')
    )
    op.create_table('risk_free_rates',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('usa_rf', sa.Float(), nullable=False),
    sa.Column('india_rf', sa.Float(), nullable=False),
    sa.Column('china_rf', sa.Float(), nullable=False),
    sa.Column('japan_rf', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('stddev_weight_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factor', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor')
    )
    op.create_table('accumulated_profit_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('accumulated_profit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('average_equity_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('average_equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('capital_employed_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('capital_employed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('capital_expenditures_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('capital_expenditures', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('cash_and_cash_equivalents_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('cash_and_cash_equivalents_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('cash_and_cash_equivalents', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('company_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['company_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'company_id')
    )
    op.create_table('comprehensive_income_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('comprehensive_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('comprehensive_income_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('comprehensive_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('cost_of_equity_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('cost_of_equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('current_debt_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('current_debt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('current_debt_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('current_debt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('debt_equity_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('debt_equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('default_spread_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('default_spread', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('depreciation_amortization_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('depreciation_amortization', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('ebit_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('ebit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('ebit_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('ebit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('eff_tax_rate_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('eff_tax_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('eff_tax_rate_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('eff_tax_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('fcfe_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fcfe', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('fcff_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fcff', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('interest_coverage_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('interest_coverage_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('interest_expense_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('interest_expense', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('interest_expense_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('interest_expense', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('interest_load_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('interest_load_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('invested_capital_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('invested_capital', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('levered_beta_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('levered_beta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('long_term_investments_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('long_term_investments', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('long_term_investments_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('long_term_investments', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('market_capitalization_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('market_capitalization', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('net_debt_issued_paid_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('net_debt_issued_paid', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('net_income_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('net_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('net_income_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('net_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('non_cash_working_capital_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('non_cash_working_capital', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('nopat_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('nopat', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('op_margin_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('op_margin_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('operating_income_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('operating_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('operating_income_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('operating_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('pre_tax_cost_of_debt_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('pre_tax_cost_of_debt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('pretax_income_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('pretax_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('pretax_income_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('pretax_income', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('price_change_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('price_change', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('rd_spend_rate_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('rd_spend_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('reinvestment_rate_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('reinvestment_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('research_and_development_expense_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('research_and_development_expense', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('retained_earnings_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('retained_earnings', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('retained_earnings_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('retained_earnings', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('revenue_yield_non_cash_working_capital_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue_yield_ncwc', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('revenues_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('revenues_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('roce_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('roce', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('roe_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('roe', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('roic_direct_upload_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('roic_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('roic_wacc_spread_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('spread_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('shareholders_equity_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('shareholders_equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('shareholders_equity_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('shareholders_equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('total_assets_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('total_assets_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('total_current_assets_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_current_assets', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('total_current_assets_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('total_current_assets', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('total_current_liabilities_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_current_liabilities', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('total_current_liabilities_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('total_current_liabilities', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('total_debt_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_debt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('total_debt_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('total_debt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('total_equity_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('total_long_term_liabilities_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_long_term_liabilities', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('total_long_term_liabilities_ttm',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Text(), nullable=False),
    sa.Column('total_long_term_liabilities', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('wacc_annual',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('wacc', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    # Seed reference tables with defaults used by the app.
    ts = datetime.utcnow().isoformat()

    op.bulk_insert(
        sa.table(
            "growth_weight_factors",
            sa.column("factor", sa.Text()),
            sa.column("weight", sa.Float()),
        ),
        [
            {"factor": "Accumulated Equity Growth", "weight": 12.0},
            {"factor": "Pretax Income Growth", "weight": 12.0},
            {"factor": "ROCE", "weight": 15.0},
            {"factor": "Net Income Growth", "weight": 20.0},
            {"factor": "ROE", "weight": 20.0},
            {"factor": "Revenue Growth", "weight": 15.0},
            {"factor": "Operating Margin", "weight": 20.0},
            {"factor": "YoY Operating Margin Growth", "weight": 20.0},
            {"factor": "NOPAT Growth", "weight": 15.0},
            {"factor": "FCFF Growth", "weight": 15.0},
            {"factor": "Earnings Power Change %", "weight": 20.0},
            {"factor": "Change in EP Delta", "weight": 20.0},
            {"factor": "Spread", "weight": 20.0},
        ],
    )

    op.bulk_insert(
        sa.table(
            "stddev_weight_factors",
            sa.column("factor", sa.Text()),
            sa.column("weight", sa.Float()),
        ),
        [
            {"factor": "Revenue Growth", "weight": 20.0},
            {"factor": "Net Income  Growth", "weight": 20.0},
            {"factor": "Operating Margin", "weight": 20.0},
            {"factor": "ROE", "weight": 20.0},
            {"factor": "ROCE", "weight": 20.0},
            {"factor": "Pretax Income Growth", "weight": 15.0},
            {"factor": "Accumulated Equity Growth", "weight": 15.0},
            {"factor": "NOPAT Growth", "weight": 15.0},
            {"factor": "YoY Operating Margin Growth", "weight": 12.0},
            {"factor": "Earnings Power Change %", "weight": 10.0},
            {"factor": "Change in EP Delta", "weight": 10.0},
            {"factor": "Spread", "weight": 10.0},
            {"factor": "FCFF Growth", "weight": 10.0},
        ],
    )

    op.bulk_insert(
        sa.table(
            "risk_free_rates",
            sa.column("year", sa.Integer()),
            sa.column("usa_rf", sa.Float()),
            sa.column("india_rf", sa.Float()),
            sa.column("china_rf", sa.Float()),
            sa.column("japan_rf", sa.Float()),
            sa.column("updated_at", sa.Text()),
        ),
        [
            {"year": 2015, "usa_rf": 2.14, "india_rf": 7.70, "china_rf": 3.40, "japan_rf": 0.36, "updated_at": ts},
            {"year": 2016, "usa_rf": 1.84, "india_rf": 6.95, "china_rf": 2.90, "japan_rf": -0.06, "updated_at": ts},
            {"year": 2017, "usa_rf": 2.33, "india_rf": 6.70, "china_rf": 3.60, "japan_rf": 0.05, "updated_at": ts},
            {"year": 2018, "usa_rf": 2.91, "india_rf": 7.70, "china_rf": 3.60, "japan_rf": 0.07, "updated_at": ts},
            {"year": 2019, "usa_rf": 2.14, "india_rf": 6.70, "china_rf": 3.20, "japan_rf": -0.10, "updated_at": ts},
            {"year": 2020, "usa_rf": 0.89, "india_rf": 5.95, "china_rf": 2.90, "japan_rf": 0.01, "updated_at": ts},
            {"year": 2021, "usa_rf": 1.45, "india_rf": 6.20, "china_rf": 2.95, "japan_rf": 0.07, "updated_at": ts},
            {"year": 2022, "usa_rf": 2.95, "india_rf": 7.29, "china_rf": 2.75, "japan_rf": 0.23, "updated_at": ts},
            {"year": 2023, "usa_rf": 3.96, "india_rf": 7.18, "china_rf": 2.70, "japan_rf": 0.56, "updated_at": ts},
            {"year": 2024, "usa_rf": 4.25, "india_rf": 6.95, "china_rf": 2.30, "japan_rf": 0.92, "updated_at": ts},
            {"year": 2025, "usa_rf": 4.00, "india_rf": 6.49, "china_rf": 1.83, "japan_rf": 1.80, "updated_at": ts},
        ],
    )

    op.bulk_insert(
        sa.table(
            "index_annual_price_movement",
            sa.column("year", sa.Integer()),
            sa.column("nasdaq_composite", sa.Float()),
            sa.column("sp500", sa.Float()),
            sa.column("updated_at", sa.Text()),
        ),
        [
            {"year": 2015, "nasdaq_composite": 5.70, "sp500": -0.70, "updated_at": ts},
            {"year": 2016, "nasdaq_composite": 7.50, "sp500": 9.50, "updated_at": ts},
            {"year": 2017, "nasdaq_composite": 28.20, "sp500": 19.40, "updated_at": ts},
            {"year": 2018, "nasdaq_composite": -3.90, "sp500": -6.20, "updated_at": ts},
            {"year": 2019, "nasdaq_composite": 35.20, "sp500": 28.90, "updated_at": ts},
            {"year": 2020, "nasdaq_composite": 43.60, "sp500": 16.30, "updated_at": ts},
            {"year": 2021, "nasdaq_composite": 21.40, "sp500": 26.90, "updated_at": ts},
            {"year": 2022, "nasdaq_composite": -33.10, "sp500": -19.40, "updated_at": ts},
            {"year": 2023, "nasdaq_composite": 43.40, "sp500": 24.20, "updated_at": ts},
            {"year": 2024, "nasdaq_composite": 28.60, "sp500": 23.30, "updated_at": ts},
            {"year": 2025, "nasdaq_composite": 19.20, "sp500": 15.00, "updated_at": ts},
        ],
    )

    op.bulk_insert(
        sa.table(
            "implied_equity_risk_premium_usa",
            sa.column("year", sa.Integer()),
            sa.column("implied_erp", sa.Float()),
            sa.column("notes", sa.Text()),
            sa.column("updated_at", sa.Text()),
        ),
        [
            {"year": 2010, "implied_erp": 4.36, "notes": "Recovery from 2008 Financial Crisis.", "updated_at": ts},
            {"year": 2011, "implied_erp": 5.20, "notes": "Recovery from 2010 flash crash/jitters.", "updated_at": ts},
            {"year": 2012, "implied_erp": 6.01, "notes": "Eurozone debt crisis fears.", "updated_at": ts},
            {"year": 2013, "implied_erp": 5.78, "notes": "Fiscal cliff concerns early in the year.", "updated_at": ts},
            {"year": 2014, "implied_erp": 4.96, "notes": "Low volatility environment.", "updated_at": ts},
            {"year": 2015, "implied_erp": 5.78, "notes": "Steady recovery pricing.", "updated_at": ts},
            {"year": 2016, "implied_erp": 6.12, "notes": "Concerns over China growth and oil price crash.", "updated_at": ts},
            {"year": 2017, "implied_erp": 5.69, "notes": "Post-election uncertainty and growth hopes.", "updated_at": ts},
            {"year": 2018, "implied_erp": 5.08, "notes": "Tax cuts enacted; steady growth expectations.", "updated_at": ts},
            {"year": 2019, "implied_erp": 5.96, "notes": "Higher risk pricing following late 2018 market drop.", "updated_at": ts},
            {"year": 2020, "implied_erp": 5.20, "notes": "Pre-pandemic level (spiked to >6.0% in March 2020).", "updated_at": ts},
            {"year": 2021, "implied_erp": 4.72, "notes": "Post-COVID recovery optimism.", "updated_at": ts},
            {"year": 2022, "implied_erp": 4.24, "notes": "Low ERP at start of year before inflation/rates spiked.", "updated_at": ts},
            {"year": 2023, "implied_erp": 5.94, "notes": "Spike due to high inflation and aggressive Fed hikes.", "updated_at": ts},
            {"year": 2024, "implied_erp": 4.60, "notes": "Decreased from 2023 as inflation fears eased.", "updated_at": ts},
            {"year": 2025, "implied_erp": 4.33, "notes": "Market priced for \"soft landing\" despite high rates.", "updated_at": ts},
        ],
    )

    op.bulk_insert(
        sa.table(
            "country_risk_premium",
            sa.column("year", sa.Integer()),
            sa.column("india", sa.Float()),
            sa.column("china", sa.Float()),
            sa.column("japan", sa.Float()),
            sa.column("us", sa.Float()),
            sa.column("uk", sa.Float()),
            sa.column("uae", sa.Float()),
            sa.column("updated_at", sa.Text()),
        ),
        [
            {"year": 2015, "india": 3.46, "china": 0.95, "japan": 1.11, "us": 0.00, "uk": 0.63, "uae": 0.78, "updated_at": ts},
            {"year": 2016, "india": 3.13, "china": 0.86, "japan": 1.00, "us": 0.00, "uk": 0.56, "uae": 0.71, "updated_at": ts},
            {"year": 2017, "india": 2.19, "china": 0.81, "japan": 0.81, "us": 0.00, "uk": 0.57, "uae": 0.57, "updated_at": ts},
            {"year": 2018, "india": 2.64, "china": 0.98, "japan": 0.98, "us": 0.00, "uk": 0.69, "uae": 0.69, "updated_at": ts},
            {"year": 2019, "india": 1.88, "china": 0.69, "japan": 0.69, "us": 0.00, "uk": 0.49, "uae": 0.49, "updated_at": ts},
            {"year": 2020, "india": 2.13, "china": 0.68, "japan": 0.68, "us": 0.00, "uk": 0.59, "uae": 0.48, "updated_at": ts},
            {"year": 2021, "india": 2.18, "china": 0.70, "japan": 0.70, "us": 0.00, "uk": 0.60, "uae": 0.49, "updated_at": ts},
            {"year": 2022, "india": 3.79, "china": 1.22, "japan": 1.22, "us": 0.00, "uk": 1.03, "uae": 0.85, "updated_at": ts},
            {"year": 2023, "india": 3.21, "china": 1.03, "japan": 1.03, "us": 0.00, "uk": 0.88, "uae": 0.72, "updated_at": ts},
            {"year": 2024, "india": 2.93, "china": 0.94, "japan": 0.94, "us": 0.00, "uk": 0.80, "uae": 0.66, "updated_at": ts},
            {"year": 2025, "india": 2.85, "china": 0.91, "japan": 0.91, "us": 0.23, "uk": 0.78, "uae": 0.64, "updated_at": ts},
        ],
    )

    op.bulk_insert(
        sa.table(
            "marginal_corporate_tax_rates",
            sa.column("country", sa.Text()),
            sa.column("effective_rate", sa.Float()),
            sa.column("notes", sa.Text()),
            sa.column("updated_at", sa.Text()),
        ),
        [
            {
                "country": "USA",
                "effective_rate": 25.70,
                "notes": "Federal (21%) + State Tax (~4-5%). While the Federal rate is a flat 21%, state taxes vary by state; Texas 0%, California 8.84%. For a diversified US company, 25.7% is the standard OECD composite rate used by analysts.",
                "updated_at": ts,
            },
            {
                "country": "India",
                "effective_rate": 25.17,
                "notes": "Base (22%) + Surcharge (10%) + Cess (4%). Most major domestic companies have opted for the Section 115BAA regime. If the company is old and has not opted for this (rare for large caps now), use 34.94%.",
                "updated_at": ts,
            },
            {
                "country": "China",
                "effective_rate": 25.00,
                "notes": "Standard national rate. China has a 25% standard rate. Use 15% only if the specific company is a qualified \"High-Tech Enterprise\".",
                "updated_at": ts,
            },
            {
                "country": "Japan",
                "effective_rate": 30.62,
                "notes": "National + Local Inhabitant + Enterprise Tax. Japan's headline rate is 23.2%, but local taxes are significant. The effective statutory tax rate for valuation is widely cited at 30.62%.",
                "updated_at": ts,
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            "industry_betas",
            sa.column("user_industry_bucket", sa.Text()),
            sa.column("mapped_sector", sa.Text()),
            sa.column("unlevered_beta", sa.Float()),
            sa.column("cash_adjusted_beta", sa.Float()),
            sa.column("updated_at", sa.Text()),
        ),
        [
            {"user_industry_bucket": "Technology : Internet Content & Info", "mapped_sector": "Software (Internet)", "unlevered_beta": 1.63, "cash_adjusted_beta": 1.69, "updated_at": ts},
            {"user_industry_bucket": "Technology : Semiconductors", "mapped_sector": "Semiconductor", "unlevered_beta": 1.36, "cash_adjusted_beta": 1.45, "updated_at": ts},
            {"user_industry_bucket": "Technology : Semi. Equip & Materials", "mapped_sector": "Semiconductor Equip", "unlevered_beta": 1.35, "cash_adjusted_beta": 1.44, "updated_at": ts},
            {"user_industry_bucket": "Technology : Software - Infrastructure", "mapped_sector": "Software (System & Application)", "unlevered_beta": 1.20, "cash_adjusted_beta": 1.22, "updated_at": ts},
            {"user_industry_bucket": "Technology : Software - Application", "mapped_sector": "Software (System & Application)", "unlevered_beta": 1.20, "cash_adjusted_beta": 1.22, "updated_at": ts},
            {"user_industry_bucket": "Technology : Scientific Instruments", "mapped_sector": "Electrical Equipment", "unlevered_beta": 1.20, "cash_adjusted_beta": 1.23, "updated_at": ts},
            {"user_industry_bucket": "Technology : Computer Hardware", "mapped_sector": "Computers/Peripherals", "unlevered_beta": 1.10, "cash_adjusted_beta": 1.12, "updated_at": ts},
            {"user_industry_bucket": "Technology : IT Services", "mapped_sector": "Computer Services", "unlevered_beta": 1.03, "cash_adjusted_beta": 1.09, "updated_at": ts},
            {"user_industry_bucket": "Technology : Electronic Components", "mapped_sector": "Electronics (General)", "unlevered_beta": 1.01, "cash_adjusted_beta": 1.03, "updated_at": ts},
            {"user_industry_bucket": "Technology : Comm. Equipment", "mapped_sector": "Telecom. Equipment", "unlevered_beta": 0.91, "cash_adjusted_beta": 0.95, "updated_at": ts},
            {"user_industry_bucket": "Technology : Electronics & Distribution", "mapped_sector": "Retail (Distributors)", "unlevered_beta": 0.91, "cash_adjusted_beta": 0.93, "updated_at": ts},
            {"user_industry_bucket": "Technology : Consumer Electronics", "mapped_sector": "Electronics (Consumer & Office)", "unlevered_beta": 0.84, "cash_adjusted_beta": 0.95, "updated_at": ts},
            {"user_industry_bucket": "Technology : Solar", "mapped_sector": "Green & Renewable Energy", "unlevered_beta": 0.49, "cash_adjusted_beta": 0.50, "updated_at": ts},
            {"user_industry_bucket": "Technology : Telecom (Wireless)", "mapped_sector": "Telecom (Wireless)", "unlevered_beta": 0.57, "cash_adjusted_beta": 0.59, "updated_at": ts},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wacc_annual')
    op.drop_table('total_long_term_liabilities_ttm')
    op.drop_table('total_long_term_liabilities_annual')
    op.drop_table('total_equity_annual')
    op.drop_table('total_debt_ttm')
    op.drop_table('total_debt_annual')
    op.drop_table('total_current_liabilities_ttm')
    op.drop_table('total_current_liabilities_annual')
    op.drop_table('total_current_assets_ttm')
    op.drop_table('total_current_assets_annual')
    op.drop_table('total_assets_ttm')
    op.drop_table('total_assets_annual')
    op.drop_table('shareholders_equity_ttm')
    op.drop_table('shareholders_equity_annual')
    op.drop_table('roic_wacc_spread_annual')
    op.drop_table('roic_direct_upload_annual')
    op.drop_table('roe_annual')
    op.drop_table('roce_annual')
    op.drop_table('revenues_ttm')
    op.drop_table('revenues_annual')
    op.drop_table('revenue_yield_non_cash_working_capital_annual')
    op.drop_table('retained_earnings_ttm')
    op.drop_table('retained_earnings_annual')
    op.drop_table('research_and_development_expense_annual')
    op.drop_table('reinvestment_rate_annual')
    op.drop_table('rd_spend_rate_annual')
    op.drop_table('price_change_annual')
    op.drop_table('pretax_income_ttm')
    op.drop_table('pretax_income_annual')
    op.drop_table('pre_tax_cost_of_debt_annual')
    op.drop_table('operating_income_ttm')
    op.drop_table('operating_income_annual')
    op.drop_table('op_margin_ttm')
    op.drop_table('op_margin_annual')
    op.drop_table('nopat_annual')
    op.drop_table('non_cash_working_capital_annual')
    op.drop_table('net_income_ttm')
    op.drop_table('net_income_annual')
    op.drop_table('net_debt_issued_paid_annual')
    op.drop_table('market_capitalization_annual')
    op.drop_table('long_term_investments_ttm')
    op.drop_table('long_term_investments_annual')
    op.drop_table('levered_beta_annual')
    op.drop_table('invested_capital_annual')
    op.drop_table('interest_load_annual')
    op.drop_table('interest_expense_ttm')
    op.drop_table('interest_expense_annual')
    op.drop_table('interest_coverage_annual')
    op.drop_table('fcff_annual')
    op.drop_table('fcfe_annual')
    op.drop_table('eff_tax_rate_ttm')
    op.drop_table('eff_tax_rate_annual')
    op.drop_table('ebit_ttm')
    op.drop_table('ebit_annual')
    op.drop_table('depreciation_amortization_annual')
    op.drop_table('default_spread_annual')
    op.drop_table('debt_equity_annual')
    op.drop_table('current_debt_ttm')
    op.drop_table('current_debt_annual')
    op.drop_table('cost_of_equity_annual')
    op.drop_table('comprehensive_income_ttm')
    op.drop_table('comprehensive_income_annual')
    op.drop_table('company_group_members')
    op.drop_table('cash_and_cash_equivalents_ttm')
    op.drop_table('cash_and_cash_equivalents_annual')
    op.drop_table('capital_expenditures_annual')
    op.drop_table('capital_employed_annual')
    op.drop_table('average_equity_annual')
    op.drop_table('accumulated_profit_annual')
    op.drop_table('stddev_weight_factors')
    op.drop_table('risk_free_rates')
    op.drop_table('marginal_corporate_tax_rates')
    op.drop_table('industry_betas')
    op.drop_table('index_annual_price_movement')
    op.drop_table('implied_equity_risk_premium_usa')
    op.drop_table('growth_weight_factors')
    op.drop_table('country_risk_premium')
    op.drop_table('company_groups')
    op.drop_table('companies')
    # ### end Alembic commands ###

