export interface IndustryLanguage {
  lens: string;
  growthQuestion: string;
  revenueSubject: string;
  costSupport: string;
  leverageExplanation: string;
  capitalBase: string;
}

const neutral: IndustryLanguage = {
  lens: "Business operations",
  growthQuestion: "How steadily did the company’s operating engine grow?",
  revenueSubject: "Company revenue",
  costSupport: "production, delivery and customer support",
  leverageExplanation: "This compares net borrowings with one year of EBITDA from the company’s operating engine. Lower is generally lighter; a negative number means cash exceeded debt.",
  capitalBase: "operating assets and working capital",
};

const matches = (bucket: string, terms: string[]) => terms.some((term) => bucket.includes(term));

export function languageForIndustryBucket(industryBucket?: string): IndustryLanguage {
  const bucket = String(industryBucket || "").toLowerCase();
  if (!bucket || bucket === "unclassified") return neutral;

  if (matches(bucket, ["bank", "finance", "financial", "payments", "fintech", "brokerage", "insurance", "wealth management", "exchange", "ratings"])) {
    return {
      lens: "Financial network",
      growthQuestion: "How steadily did customer activity and the financial network translate into revenue?",
      revenueSubject: "Revenue from the financial franchise",
      costSupport: "distribution, technology, servicing and regulatory operations",
      leverageExplanation: "For a financial company, borrowings can be part of the product rather than ordinary corporate leverage. Net Debt/EBITDA is shown for consistency, but should not be read like an industrial-company debt ratio.",
      capitalBase: "the financial franchise, technology and regulatory capital",
    };
  }
  if (matches(bucket, ["healthcare", "pharma", "therapeutic", "biotech", "clinical", "medical", "hospital", "diagnostic", "life science"])) {
    return {
      lens: "Care and treatment engine",
      growthQuestion: "How steadily did demand for care, treatments or medical products translate into revenue?",
      revenueSubject: "Healthcare revenue",
      costSupport: "clinical delivery, product development, manufacturing and market access",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from care delivery or medical products. Lower is generally lighter; a negative number means cash exceeded debt.",
      capitalBase: "care facilities, treatment platforms, intellectual property and working capital",
    };
  }
  if (matches(bucket, ["semiconductor", "photon", "electronic component", "chip", "memory", "foundry", "silicon", "optical", "compute hardware", "server", "storage systems"])) {
    return {
      lens: "Compute and electronics engine",
      growthQuestion: "How steadily did demand for chips, systems or electronic components translate into revenue?",
      revenueSubject: "Revenue from compute and electronic products",
      costSupport: "engineering, fabrication capacity, supply-chain inputs and customer qualification",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from the hardware cycle. Lower is generally lighter; a negative number means cash exceeded debt.",
      capitalBase: "fabs, equipment, design intellectual property and working capital",
    };
  }
  if (matches(bucket, ["cloud", "software", "data platform", "database", "cyber", "devops", "digital transformation", "information technology", "it services", "internet platform", "workflow", "artificial intelligence"])) {
    return {
      lens: "Software and platform engine",
      growthQuestion: "How steadily did customer adoption, subscriptions or platform usage translate into revenue?",
      revenueSubject: "Software and platform revenue",
      costSupport: "engineering, infrastructure delivery and customer acquisition",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from the software and platform engine. Lower is generally lighter; a negative number means cash exceeded debt.",
      capitalBase: "software platforms, data infrastructure, intellectual property and working capital",
    };
  }
  if (matches(bucket, ["telecom", "communication equipment", "networking", "connectivity", "broadband", "satellite"])) {
    return {
      lens: "Connectivity network",
      growthQuestion: "How steadily did subscribers, traffic and network demand translate into revenue?",
      revenueSubject: "Connectivity revenue",
      costSupport: "network capacity, service delivery and customer acquisition",
      leverageExplanation: "This compares net borrowings with one year of EBITDA generated by the connectivity network. Lower is generally lighter; a negative number means cash exceeded debt.",
      capitalBase: "network equipment, spectrum, fibre and working capital",
    };
  }
  if (matches(bucket, ["restaurant", "retail", "consumer", "apparel", "furnishing", "appliance", "food", "grocery", "leisure", "travel", "e-commerce", "marketplace", "commerce", "automobile", "auto manufacturer", "auto parts"])) {
    return {
      lens: "Consumer demand engine",
      growthQuestion: "How steadily did customer demand, transactions and product sales translate into revenue?",
      revenueSubject: "Consumer-facing revenue",
      costSupport: "merchandise or production, distribution, stores and customer acquisition",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from serving customers. Lower is generally lighter; a negative number means cash exceeded debt.",
      capitalBase: "brands, stores or distribution assets, inventory and working capital",
    };
  }
  if (matches(bucket, ["oil", "gas", "energy", "refining", "fuel", "uranium", "coal"])) {
    return {
      lens: "Energy production chain",
      growthQuestion: "How steadily did production, throughput and commodity pricing translate into revenue?",
      revenueSubject: "Energy-chain revenue",
      costSupport: "production, processing, transport and field operations",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from the energy cycle. Lower is generally lighter, while commodity swings can move the ratio sharply.",
      capitalBase: "reserves, plants, pipelines, equipment and working capital",
    };
  }
  if (matches(bucket, ["utility", "electric", "power", "water", "renewable", "grid", "transmission", "switchgear", "transformer"])) {
    return {
      lens: "Essential infrastructure network",
      growthQuestion: "How steadily did regulated demand, capacity and infrastructure usage translate into revenue?",
      revenueSubject: "Infrastructure-network revenue",
      costSupport: "generation or supply capacity, network maintenance and customer service",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from essential infrastructure. Debt is often structural here, so stability and regulation matter alongside the ratio.",
      capitalBase: "generation, grid or water infrastructure and working capital",
    };
  }
  if (matches(bucket, ["logistics", "shipping", "trucking", "airline", "airport", "railroad", "freight", "transport", "ports", "fleet"])) {
    return {
      lens: "Transport and logistics network",
      growthQuestion: "How steadily did freight, passenger or network activity translate into revenue?",
      revenueSubject: "Transport and logistics revenue",
      costSupport: "fleet capacity, fuel, labour, terminals and network operations",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from the transport network. Lower is generally lighter, while fleet ownership can make debt structurally important.",
      capitalBase: "fleet, terminals, routes and working capital",
    };
  }
  if (matches(bucket, ["industrial", "construction", "machinery", "equipment", "engineering", "aerospace", "defense", "automation", "manufacturing", "building products", "electrical", "tools"])) {
    return {
      lens: "Industrial order-and-delivery engine",
      growthQuestion: "How steadily did orders, project execution and equipment deliveries translate into revenue?",
      revenueSubject: "Industrial and project revenue",
      costSupport: "materials, manufacturing capacity, engineering and project execution",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from the industrial order book. Lower is generally lighter; a negative number means cash exceeded debt.",
      capitalBase: "factories, equipment, project assets and working capital",
    };
  }
  if (matches(bucket, ["chemical", "cement", "steel", "metal", "mining", "mineral", "materials", "paper", "pulp", "graphite", "carbon", "polymer", "resin", "petrochemical"])) {
    return {
      lens: "Materials and processing engine",
      growthQuestion: "How steadily did volumes, capacity utilisation and pricing translate into revenue?",
      revenueSubject: "Materials revenue",
      costSupport: "feedstocks, energy, processing capacity and distribution",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from the materials cycle. Lower is generally lighter, while commodity pricing can make the ratio move sharply.",
      capitalBase: "mines or plants, processing equipment, inventory and working capital",
    };
  }
  if (matches(bucket, ["agricultural", "fertilizer", "agro", "farm"])) {
    return {
      lens: "Agricultural input cycle",
      growthQuestion: "How steadily did farm demand, input volumes and pricing translate into revenue?",
      revenueSubject: "Agricultural-input revenue",
      costSupport: "feedstocks, manufacturing, seasonal inventory and distribution",
      leverageExplanation: "This compares net borrowings with one year of EBITDA across the agricultural cycle. Lower is generally lighter, while crop and commodity cycles can move it sharply.",
      capitalBase: "production assets, distribution capacity, seasonal inventory and working capital",
    };
  }
  if (matches(bucket, ["media", "advertising", "gaming", "entertainment", "broadcast", "publishing", "creator", "social"])) {
    return {
      lens: "Audience and content engine",
      growthQuestion: "How steadily did audience, engagement and monetisation translate into revenue?",
      revenueSubject: "Audience and content revenue",
      costSupport: "content, technology, distribution and audience acquisition",
      leverageExplanation: "This compares net borrowings with one year of EBITDA from the audience and content engine. Lower is generally lighter; a negative number means cash exceeded debt.",
      capitalBase: "content rights, platforms, production assets and working capital",
    };
  }
  return neutral;
}
